// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_entity.Models;

#nullable disable

namespace dotnet_entity.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251003143630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("dotnet_entity.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Apple Watch",
                            Aktif = true,
                            Fiyat = 40000m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Apple Telefon",
                            Aktif = true,
                            Fiyat = 30000m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Apple Kalem",
                            Aktif = true,
                            Fiyat = 20000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
