// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_entity.Models;

#nullable disable

namespace dotnet_entity.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251117140421_UpdateUrunEntity")]
    partial class UpdateUrunEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("dotnet_entity.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Apple Watch Serisi 7",
                            Ad = "Apple Watch",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 40000m,
                            Resim = "1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Apple iPhone 13 Pro Max",
                            Ad = "Apple Telefon",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 30000m,
                            Resim = "2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Apple Pencil 2.Nesil",
                            Ad = "Apple Kalem",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 20000m,
                            Resim = "3.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Apple iPad Pro 2021",
                            Ad = "Apple Tablet",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 25000m,
                            Resim = "4.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Apple MacBook Pro M1",
                            Ad = "Apple Laptop",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 50000m,
                            Resim = "5.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Apple AirPods Pro",
                            Ad = "Apple Kulaklık",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 15000m,
                            Resim = "6.jpeg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
